import Providers from "@/components/Providers";
import "@/styles/globals.css";

import { Inter } from "next/font/google";
import Script from "next/script";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata = {
    title: "Trevor 2024 Senior Assassin",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`font-sans ${inter.variable}`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
